server:
  port: 8084

spring:
  application:
    name: catalog-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka