server:
  port: 8082

spring:
  application:
    name: inventory-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
